/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { EmptyResponseDto } from './emptyResponseDto';
import type { ErrorResponseDto } from './errorResponseDto';

export type ApiV1QuestionDelete200 = EmptyResponseDto | ErrorResponseDto;
