/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiV1QuestionDeliveredList200Data } from './apiV1QuestionDeliveredList200Data';

export type ApiV1QuestionDeliveredList200 = {
  data: ApiV1QuestionDeliveredList200Data;
};
