/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiV1DeliveryList200DataDates } from './apiV1DeliveryList200DataDates';

export type ApiV1DeliveryList200Data = {
  dates?: ApiV1DeliveryList200DataDates;
  deliveryWeekdays?: string[];
  isTodayPast?: boolean;
  latestUpdate?: number;
};
