/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionOptionSaveRequestDto } from './questionOptionSaveRequestDto';

export type ApiV1QuestionUpdateBody = {
  questionDescription?: string;
  questionId?: string;
  questionName?: string;
  questionOptions?: QuestionOptionSaveRequestDto[];
};
