/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiV1QuestionImportBodyQuestionsItemQuestion } from './apiV1QuestionImportBodyQuestionsItemQuestion';

export type ApiV1QuestionImportBodyQuestionsItem = {
  question?: ApiV1QuestionImportBodyQuestionsItemQuestion;
  questionPlacement?: string;
};
