/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiV1QuestionImportBodyQuestionsItem } from './apiV1QuestionImportBodyQuestionsItem';

export type ApiV1QuestionImportBody = {
  questionPlacement?: string;
  questions?: ApiV1QuestionImportBodyQuestionsItem[];
};
