/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiV1QuestionDeliveryStatus200Data } from './apiV1QuestionDeliveryStatus200Data';

export type ApiV1QuestionDeliveryStatus200 = {
  data: ApiV1QuestionDeliveryStatus200Data;
};
