/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { DeliveryDateResponseDto } from './deliveryDateResponseDto';

export type ApiV1DeliveryList200DataDates = DeliveryDateResponseDto | string[];
