/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiV1DeliveryListDates200OneOf } from './apiV1DeliveryListDates200OneOf';
import type { EmptyResponseDto } from './emptyResponseDto';

export type ApiV1DeliveryListDates200 = ApiV1DeliveryListDates200OneOf | EmptyResponseDto;
