/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * quiz-openapi
 * OpenAPI documentation of CKQuiz API endpoints.
 * OpenAPI spec version: 1.0.0
 */

export interface DeliveryDateResponseDto {
  deliveryDate?: string;
  deliveryDateId?: string | null;
  isDelivery?: boolean;
  questionId?: string;
}
